-- HongStargram 추가 기능을 위한 데이터베이스 스키마
-- Oracle Database용 테이블 생성 스크립트

-- 1. 루틴 테이블 (사용자의 루틴 정보)
CREATE TABLE ROUTINES (
    ROUTINE_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    COLOR VARCHAR2(20) DEFAULT '#0095F6',
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ROUTINE_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 루틴 ID 시퀀스
CREATE SEQUENCE ROUTINE_SEQ START WITH 1 INCREMENT BY 1;

-- 2. 루틴 이벤트 테이블 (루틴 일정)
CREATE TABLE ROUTINE_EVENTS (
    EVENT_ID NUMBER PRIMARY KEY,
    ROUTINE_ID NUMBER NOT NULL,
    EVENT_DATE DATE NOT NULL,
    EVENT_TIME VARCHAR2(10),
    IS_COMPLETED CHAR(1) DEFAULT 'N',
    COMPLETED_AT DATE,
    CONSTRAINT FK_EVENT_ROUTINE FOREIGN KEY (ROUTINE_ID) REFERENCES ROUTINES(ROUTINE_ID) ON DELETE CASCADE
);

-- 이벤트 ID 시퀀스
CREATE SEQUENCE EVENT_SEQ START WITH 1 INCREMENT BY 1;

-- 3. 사용자 위치 테이블
CREATE TABLE USER_LOCATIONS (
    USER_ID VARCHAR2(50) PRIMARY KEY,
    LATITUDE NUMBER(10, 6) NOT NULL,
    LONGITUDE NUMBER(10, 6) NOT NULL,
    LOCATION_NAME VARCHAR2(200),
    UPDATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_LOCATION_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 4. 위치 기반 알람 테이블
CREATE TABLE LOCATION_ALERTS (
    ALERT_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    TARGET_USER_ID VARCHAR2(50) NOT NULL,
    ALERT_DISTANCE NUMBER(10, 2) DEFAULT 1000,
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ALERT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ALERT_TARGET FOREIGN KEY (TARGET_USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 알람 ID 시퀀스
CREATE SEQUENCE ALERT_SEQ START WITH 1 INCREMENT BY 1;

-- 인덱스 생성 (성능 향상)
CREATE INDEX IDX_ROUTINES_USER ON ROUTINES(USER_ID);
CREATE INDEX IDX_EVENTS_ROUTINE ON ROUTINE_EVENTS(ROUTINE_ID);
CREATE INDEX IDX_EVENTS_DATE ON ROUTINE_EVENTS(EVENT_DATE);
CREATE INDEX IDX_ALERTS_USER ON LOCATION_ALERTS(USER_ID);
CREATE INDEX IDX_ALERTS_TARGET ON LOCATION_ALERTS(TARGET_USER_ID);

COMMIT;
